# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        # Filename for the release
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build:prod
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with: 
        directory: ./
        type: zip
        filename: ${{ github.ref_name }}-${{ github.run_id }}.zip # default is release.zip
        path: ./gryphon-games-dist/
    - name: Add zipped plugin as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.GITHUB_REF_NAME }}-${{ github.GITHUB_RUN_ID }}.zip
        path: ${{ github.GITHUB_REF_NAME }}-${{ github.GITHUB_RUN_ID }}.zip
