# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release project CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OUTPUT_FILE: ${{ github.ref_name }}-${{ github.run_id }}.zip

jobs:
  test:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        # Filename for the release
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build:prod
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with: 
        directory: ./gryphon-games-dist/
        type: zip
        filename: ${{ env.OUTPUT_FILE }} # default is release.zip
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./gryphon-games-dist/${{ env.OUTPUT_FILE }}
        generateReleaseNotes: true
        commit: ${{ github.sha }}
        tag: ${{ github.run_number }}
        name: gryphon-games-${{ github.run_number }}
        
        